export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import {Toaster} from 'react-hot-toast'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head />
       
      <body>
        <header><h1>Our customes list</h1></header>
        {children}
         <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
